% Example script to load ScouseTom datasets
% data is stored in the folder selected in a .mat
% output is structure which contains 
% all info about the file, as well as boundary voltages etc.

%% load single frequency data

%load boundary voltages of resistor phantom recording. The log files
%generated by the ScouseTom ssytem are located in same directory
[BVstruc_TD]=ScouseTom_LoadBV('..\resources\data\ScouseTom\forreal_2_clean.bdf');

%% load Multifrequency data

%load boundary voltages of resistor phantom recording using multiple
%frequwncies. The log files generated by the ScouseTom system is located in
%the same directory
[BVstruc_MF]=ScouseTom_LoadBV('..\resources\data\ScouseTom\MultiFreq.bdf');

%% load contact impedance check

% perform contact impedance check on data collected on scalp with EEG
% electrodes. This code is a bit different as we want to estimate the
% contact impedance and plot it quickly. The protocol is also independent
% of that set by the ExpSetup
[Zout]=ScouseTom_LoadZ('..\resources\data\ScouseTom\S1a_Z4.bdf');
